# Generated by Django 3.1.7 on 2021-03-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210316_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='thumbnails/sample.jpg', null=True, upload_to=''),
        ),
    ]
