# Generated by Django 3.2 on 2021-07-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='status',
        ),
    ]
