# Generated by Django 3.1.7 on 2021-03-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic.png', null=True, upload_to='profile_pic'),
        ),
    ]
