# Generated by Django 3.1.7 on 2021-03-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210322_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='sample.jpg', null=True, upload_to='post_pic'),
        ),
    ]
