# Generated by Django 3.1.7 on 2021-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='sample.jpg', null=True, upload_to='post_pics'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
