# Generated by Django 3.1.7 on 2021-03-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='created',
        ),
    ]
