# Generated by Django 3.1.7 on 2021-03-25 19:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='sample.jpg', null=True),
        ),
    ]
