# Generated by Django 3.1.7 on 2021-04-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_id',
            new_name='github_id',
        ),
    ]
